import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1440px" } },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        "border-strong": "hsl(var(--border-strong))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--bg))",
        foreground: "hsl(var(--ink-1))",
        bg: "hsl(var(--bg))",
        surface: "hsl(var(--surface))",
        "surface-2": "hsl(var(--surface-2))",
        "surface-3": "hsl(var(--surface-3))",
        "ink-1": "hsl(var(--ink-1))",
        "ink-2": "hsl(var(--ink-2))",
        "ink-3": "hsl(var(--ink-3))",
        "ink-4": "hsl(var(--ink-4))",
        accent: {
          DEFAULT: "hsl(var(--accent-600))",
          foreground: "hsl(var(--accent-fg))",
          50: "hsl(var(--accent-50))",
          100: "hsl(var(--accent-100))",
          500: "hsl(var(--accent-500))",
          600: "hsl(var(--accent-600))",
          700: "hsl(var(--accent-700))",
        },
        success: { DEFAULT: "hsl(var(--success-500))", 50: "hsl(var(--success-50))" },
        warn: { DEFAULT: "hsl(var(--warn-500))", 50: "hsl(var(--warn-50))" },
        danger: { DEFAULT: "hsl(var(--danger-500))" },
        info: { DEFAULT: "hsl(var(--info-500))", 50: "hsl(var(--info-50))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        status: {
          new: "hsl(var(--status-new))",
          "new-fg": "hsl(var(--status-new-fg))",
          qualified: "hsl(var(--status-qualified))",
          "qualified-fg": "hsl(var(--status-qualified-fg))",
          opportunity: "hsl(var(--status-opportunity))",
          "opportunity-fg": "hsl(var(--status-opportunity-fg))",
          won: "hsl(var(--status-won))",
          "won-fg": "hsl(var(--status-won-fg))",
          lost: "hsl(var(--status-lost))",
          "lost-fg": "hsl(var(--status-lost-fg))",
        },
      },
      borderRadius: {
        lg: "var(--radius-lg)",
        md: "var(--radius)",
        sm: "6px",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow)",
        lg: "var(--shadow-lg)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(-8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shake: {
          "0%,100%": { transform: "translateX(0)" },
          "25%": { transform: "translateX(-4px)" },
          "75%": { transform: "translateX(4px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in-up": "fade-in-up 240ms cubic-bezier(0.16, 1, 0.3, 1)",
        shake: "shake 180ms ease-in-out",
      },
    },
  },
  plugins: [animate],
} satisfies Config;
